settings:
  root_dir: "./datasets/celeba/images"
  train_anns: "./datasets/celeba/annotations/train.csv"
  val_anns: "./datasets/celeba/annotations/val.csv"

  checkpoint_path: 'weights' 
  sample_folder: 'sample'

  cuda: True
  lr: 0.001
  batch_size: 4
  num_workers: 4

  step_iters: [50000, 75000, 100000]
  gamma: 0.1
  
  # visualize_per_iter: 1
  save_per_iter: 5
  print_per_iter: 1
  num_epochs: 25

  img_size: 512

